FROM maven:3.6.3-openjdk-17 AS builder

WORKDIR /app

COPY api/pom.xml .

RUN mvn dependency:go-offline

COPY api/src ./src

RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]