export const environment = {
    production: false,
    API_URL: 'http://localhost:8080',
    API_TURMA: '/turma',
    API_TURMA_TODOS: '/turma/todasTurmas',
    API_CURSOS: '/curso',
    API_CURSOS_TODOS: '/curso/todosCursos',
    API_CURSOS_ID: '/curso/id',
    API_ALUNO: '/aluno',
    API_ALUNO_TURMA: '/aluno/turma',
    API_ALUNO_TODOS: '/aluno/todosAlunos',
    API_ALUNO_ID: '/aluno/id',
    API_ALUNO_CPF: '/aluno/cpf',
    API_ENDERECO: '/endereco',
};
